# Site settings
title: Cool Dad Productions
description: Weird little coding projects from cooldad.computer
url: "https://cooldad.computer"
author: Cole Strode

theme: jekyll-theme-console

#header_pages:
#  - index.md
#  - about.md

plugins:
  - jekyll-seo-tag
  - jekyll-feed

# social icons and sharing options
social:
  - icon:	github
    url:	https://github.com/colestrode
    desc:	Find me on Github
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	https://www.linkedin.com/in/colestrode/
    desc:	This is my corporate face
    share_url:
    share_title:
    share_link:

google_tag_manager: G-NXYERSH9X1
